export const SET_DATA = 'SET_DATA'
export const SET_DETAILS_CHECK = 'SET_DETAILS_CHECK'
export const SET_PROMO_CHECK = 'SET_PROMO_CHECK'
export const SET_DISCOUNT_CODE = 'SET_DISCOUNT_CODE'
export const SUBMIT_DISCOUNT_CODE = 'SUBMIT_DISCOUNT_CODE'



